#!/bin/sh

trap "echo -ne '\nbye'; exit 1" EXIT

if ! stow --version > /dev/null 2>&1
then
	echo "E: stow not installed or not found" 1>&2
	exit 1
fi
if [ -n "${MACH:=$1}" ]
then
	echo "I: stowing for $MACH"
else
	echo "E: MACH not set" 1>&2
	echo "Enter valid value for 'MACH'"
	echo "d(esktop) | s(erver) | l(aptop)"
	echo -n ">"
	read MACH
fi

mkdir -p "$HOME/bin"
mkdir -p "$HOME/.config"
ln -sf "$(realpath "$0")" $HOME/bin/
cd "$(dirname "$(realpath "$0")")" || exit 1
case "$MACH" in
	"desktop" | "d" | "laptop" | "l")
		stow -d bin/ -t "$HOME/bin" -R common guiscripts menuscripts extra
		stow -d config/ -t "$HOME/.config" -R essentials common extra X theme xdg hyprland
		stow -d config/ -t "$HOME/" -R home
		;;
	"server" | "s")
		stow -d bin/ -t "$HOME/bin" -R common serverscripts menuscripts
		stow -d config/ -t "$HOME/.config" -R essentials common
		stow -d config/ -t "$HOME/" -R home
		;;
	*)
		echo "E: invalid value for 'MACH'" 1>&2
		break
esac
