#!/usr/bin/env bash
battery="$(acpi -i | awk -F ',' 'NR==1 {print $2}')"
charging="$(acpi -i | awk 'NR==1 {print $3}')" 
battery=${battery:1:-1}
if [[ "${charging::-1}" == "Charging" ]]
then
    icon="<fn=1></fn>"
else
    index=$((battery/25))
    array=("<fn=1></fn>" "<fn=1></fn>" "<fn=1></fn>" "<fn=1></fn>" "<fn=1></fn>")
    icon="${array[$index]}"
fi
echo -n " ${battery}% ${icon}"
